// /*
// * This Java source file was generated by the Gradle 'init' task.
// */
// package jwt.java.examples;

// import java.io.IOException;
// import java.net.URI;

// import org.glassfish.grizzly.http.server.HttpServer;
// import org.glassfish.hk2.api.ServiceLocator;
// import org.glassfish.hk2.utilities.ServiceLocatorUtilities;
// import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;
// import org.glassfish.jersey.server.ResourceConfig;

// import jakarta.ws.rs.GET;
// import jakarta.ws.rs.Path;

// @Path("/")
// public class App {

// public static HttpServer server;

// // Base URI the Grizzly HTTP server will listen on
// public static final String BASE_URI = "http://localhost:8080/";

// /**
// * Starts Grizzly HTTP server exposing JAX-RS resources defined in this
// * application.
// *
// * @return Grizzly HTTP server.
// */
// public static HttpServer startServer() {
// // create a resource config that scans for JAX-RS resources and providers
// // in com.example package
// final ResourceConfig rc = new ResourceConfig().packages("jwt.java.examples");

// // Get a ServiceLocator
// ServiceLocator locator =
// ServiceLocatorUtilities.createAndPopulateServiceLocator();

// // create and start a new instance of grizzly http server
// // exposing the Jersey application at BASE_URI
// return GrizzlyHttpServerFactory.createHttpServer(URI.create(BASE_URI), rc,
// locator);
// }

// /**
// * Main method.
// *
// * @param args
// * @throws IOException
// */
// public static void main(String[] args) throws IOException {
// server = startServer();
// System.out.println(String.format("Jersey app started with endpoints available
// at "
// + "%s%nHit Ctrl-C to stop it...", BASE_URI));
// }

// @Path("/shutdown")
// @GET
// public void shutdown() {
// server.shutdownNow();
// }
// }
